#Load packages
require(janitor)
require(scales)
require(DT)
require(broom)
require(forcats)
require(dplyr)
require(car)
require(DT)
require(skedastic)
require(tidyr)
require(stringr)
require(plotly)
require(ggplot2)
require(readxl)
require(arrow)